version: 2
updates:
  - package-ecosystem: "terraform"
    directories:
      - "/environments/*"
      - "/modules/*"
      - "/bootstrap"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
